### ISSUE TITLE
EPIC: Brain Data Standards Ontology Release

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#88]
Status: Draft

Aim for public beta release by late June.  An internal alpha release can happen earlier.

### What we need in order to make a public beta release

ec_individuals  -> master + releases become official tag sets.

Agreement on schema:
 - We currently have two competing schemas for automating classication:  Reification & marker based.  The marker based currently appears to be very brittle, so the reification pattern seems more likely.

Stabilise IRIs 
   - [ ] Reach agreement on stable IRIs for classes and individuals
   - [ ] Move all Object properties to RO or make stable local IRIs for them - adding better definitions/use-guidance (requires review - some OPs may change)
   - [ ] Review Annotation properties, stabilise IRIs and add definitions/use-guidance
   - [ ] Agree IRI for whole ontology - should this be registered with the Foundry?
  
Sufficient schema consensus
- [ ] Reach sufficient agreement on automated definition & label patterns (should not be a blocker).
- [ ] Reach sufficient agreement on how to incorporate evidence (should not be blocker).

**Comment by shawntanzk** [comment]
everything here seems to be done, closing this EPIC, anything for new release happy to open new EPICs or Milestones
